name: currency_converter
description: A currency converter app in flutter
publish_to: 'none'
version: 1.1.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  flutter_bloc: ^7.2.0
  hydrated_bloc: ^7.0.1
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true